#!/usr/bin/env bash
# Full pipeline resume: SSH into running instance, setup, synth, pull, destroy
set -euo pipefail

HOST=ssh1.vast.ai
PORT=13594
KEY=~/.ssh/ssh_key
KNOWN=/tmp/vast_known_31813594
INSTANCE_ID=31813594
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
JOB_NAME="py-audio-box-20260221_155435"   # reuse original job name for pull dir

SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=$KNOWN -o BatchMode=yes -i $KEY -p $PORT"
RSYNC_SSH="ssh -p $PORT -i $KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=$KNOWN"

run_ssh() { ssh $SSH_OPTS "root@$HOST" "$@"; }

# ── 1. wait for SSH ──────────────────────────────────────────────────────────
echo "==> Waiting for SSH on $HOST:$PORT ..."
for i in $(seq 1 36); do
  if ssh -o ConnectTimeout=5 $SSH_OPTS "root@$HOST" 'echo __ok__' 2>/dev/null | grep -q '__ok__'; then
    echo "  ✓ SSH ready"
    break
  fi
  printf "  [%d] retrying...\n" "$i"
  sleep 10
done

# ── 2. verify environment ──────────────────────────────────────────────────
echo ""
echo "==> Environment check"
run_ssh "nvidia-smi -L && python3 -c 'import torch; print(\"torch\", torch.__version__, \"cuda\", torch.cuda.is_available())'"

# ── 3. ensure /app is ready ───────────────────────────────────────────────
echo ""
echo "==> Verifying /app on instance"
# /app is already populated by Dockerfile COPY. If ONSTART_CMD git clone succeeded,
# it may be fresher; if not (non-empty dir), the baked copy is used. Either way,
# ensure run-direct is executable and dirs exist.
run_ssh "ls /app/run-direct && chmod +x /app/run-direct && mkdir -p /work /cache"
echo "  ✓ /app ready (run-direct executable)"

# ── 4. upload voices to /cache/voices/ ───────────────────────────────────
echo ""
echo "==> Checking if voices are already uploaded on instance"
VOICE_COUNT=$(run_ssh "ls /cache/voices/ 2>/dev/null | wc -l" 2>/dev/null || echo 0)
if [[ "$VOICE_COUNT" -gt 0 ]]; then
  echo "  ✓ Voices already present on instance (${VOICE_COUNT} dirs)"
else
  echo "    Uploading voices → $HOST:/cache/voices/"
  run_ssh "mkdir -p /cache/voices"
  rsync -az --info=progress2 \
    -e "$RSYNC_SSH" \
    "${REPO_ROOT}/cache/voices/" \
    "root@${HOST}:/cache/voices/"
  echo "  ✓ Voices uploaded"
fi

# ── 5. upload text file to /work/ ────────────────────────────────────────
echo ""
echo "==> Uploading rascar_test.txt → $HOST:/work/"
# Text file lives in /tmp (generated by write_test_text.py)
TEXT_SRC="${TEXT_SRC:-/tmp/rascar_test.txt}"
[[ -f "$TEXT_SRC" ]] || { python3 "${REPO_ROOT}/tmp/write_test_text.py" "$TEXT_SRC" 2>/dev/null || die "Could not find $TEXT_SRC"; }
rsync -az \
  -e "$RSYNC_SSH" \
  "${TEXT_SRC}" \
  "root@${HOST}:/work/rascar_test.txt"
echo "  ✓ Text file uploaded"

# ── 6. list voices to confirm ─────────────────────────────────────────────
echo ""
echo "==> Checking registered voices on instance"
run_ssh "cd /app && ./run-direct voice-synth list-voices 2>&1 | head -20" || echo "  ! list-voices failed (non-fatal)"

# ── 7. run synthesis ──────────────────────────────────────────────────────
echo ""
echo "==> Running synthesis (rascar-capac, French)"
echo "    This will download the TTS model (~5-8 GB) and synthesise the text."
T0=$SECONDS
run_ssh "cd /app && ./run-direct voice-synth speak --voice rascar-capac --text-file /work/rascar_test.txt --language French"
printf "  ✓ Synthesis done  (%dm%02ds)\n" $(( (SECONDS-T0)/60 )) $(( (SECONDS-T0)%60 ))

# ── 8. list output ────────────────────────────────────────────────────────
echo ""
echo "==> Output files in /work/"
run_ssh "ls -lh /work/"

# ── 9. pull results to work_remote/ ──────────────────────────────────────
echo ""
PULL_DST="${REPO_ROOT}/work_remote/${JOB_NAME}"
echo "==> Pulling /work/ → ${PULL_DST}/"
mkdir -p "$PULL_DST"
rsync -az --progress \
  -e "$RSYNC_SSH" \
  "root@${HOST}:/work/" \
  "${PULL_DST}/"
echo "  ✓ Results pulled → work_remote/${JOB_NAME}/"

# ── 10. destroy instance ─────────────────────────────────────────────────
echo ""
echo "==> Destroying instance $INSTANCE_ID"
"${REPO_ROOT}/scripts/vast" destroy instance "$INSTANCE_ID" 2>/dev/null && echo "  ✓ Instance destroyed" || echo "  ! destroy returned non-zero (may already be gone)"

# ── done ─────────────────────────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════"
echo "  ✓  Pipeline complete"
echo "  Results: work_remote/${JOB_NAME}/"
ls -lh "${PULL_DST}/" 2>/dev/null | head -20
echo "══════════════════════════════════════════════"
